################################################################################
# ntpgps.conf
#
# Copyright (C) 2025 Richard Elwell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

# Generic NMEA GPS Receiver
#  mode is 9600 baud + $GPZDA only
#  /dev/gpsN for NMEA
#  /dev/gpsppsN for PPS
#  https://www.eecis.udel.edu/~mills/ntp/html/drivers/driver20.html

# /dev/gps10, /dev/gpspps10
server 127.127.20.10 mode 24 prefer true # select bitrate, $GPZDA
fudge 127.127.20.10 refid GPS # an ASCII string from one to four characters, with default GPS
fudge 127.127.20.10 stratum 0 # the driver stratum, in decimal from 0 to 15, with default 0
fudge 127.127.20.10 flag1 1 # Enable PPS signal processing
fudge 127.127.20.10 flag2 0 # Capture the pulse on the rising edge
fudge 127.127.20.10 flag3 1 # Use the kernel discipline
fudge 127.127.20.10 flag4 1 # Obscures location in timecode

# /dev/gps20
#server 127.127.20.20 mode 24 prefer true # select bitrate, $GPZDA
#fudge 127.127.20.20 refid GPS # an ASCII string from one to four characters, with default GPS
#fudge 127.127.20.20 stratum 0 # the driver stratum, in decimal from 0 to 15, with default 0
#fudge 127.127.20.20 flag4 1 # Obscures location in timecode

# /dev/gps30
server 127.127.20.30 mode 24 prefer true # select bitrate, $GPZDA
fudge 127.127.20.30 refid GPS # an ASCII string from one to four characters, with default GPS
fudge 127.127.20.30 stratum 0 # the driver stratum, in decimal from 0 to 15, with default 0
fudge 127.127.20.30 flag4 1 # Obscures location in timecode


# Undisciplined Local Clock
# https://www.eecis.udel.edu/~mills/ntp/html/drivers/driver1.html
# https://www.eecis.udel.edu/~mills/ntp/html/clockopt.html
#server 127.127.1.0
#fudge 127.127.1.0 stratum 5 # the driver stratum, in decimal from 0 to 15, with default 5
#fudge 127.127.1.0 refid LOCL # an ASCII string from one to four characters, with default LOCL

