################################################################################
# nmea_gps%N.conf
#
# Copyright (C) 2025 Richard Elwell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

# Generic NMEA GPS Receiver
#  mode is 9600 baud + $GPZDA only
#  /dev/gpsN for NMEA
#  https://www.eecis.udel.edu/~mills/ntp/html/drivers/driver20.html

# /dev/gps%N
server 127.127.20.%N mode 24 prefer true # select bitrate, $GPZDA, truechimer
fudge 127.127.20.%N refid GPS # an ASCII string from one to four characters, with default GPS
fudge 127.127.20.%N stratum 0 # the driver stratum, in decimal from 0 to 15, with default 0
fudge 127.127.20.%N flag4 1 # Obscures location in timecode

